version: "3.9"

networks:
  net1:

services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: django_adv
    ports:
      - "5432:5432"
    networks:
      net1:
        aliases:
          - database